version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "face-recognition-cloud"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-v1jup8z23h79"
s3_prefix = "face-recognition-cloud"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
